#spring.application.name=ecomerce_website
#config port -> http://localhost:1311/ecomerce/

server:
  port: 1311
  servlet:
    context-path: /ecomerce

spring:
  application:
    name: "ecomerce_website"

  datasource:
    url: "jdbc:mysql://localhost:3306/ecomerce"
    username: "root"
    password: "Admin@123"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


app:
  page-size: 5

